- id: '1530347786562'
  alias: Entrance presence
  trigger:
  - entity_id: light.tradfri_bulb_e14_ws_opal_400lm
    from: 'off'
    platform: state
    to: 'on'
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: device_tracker.huawei_mate_9_pro9daa4a7
      state: not_home
    - after: '22:00'
      before: 08:00
      condition: time
  action:
  - data:
      message: Precense detected in entrance
      title: Entrance presence alert
    service: notify.pushbullet_notifier
- id: '1531068777832'
  alias: Nightly rain
  trigger:
  - at: '21:00'
    platform: time
  condition:
  - condition: template
    value_template: '{{ states.sensor.rain_probability.attributes.hourly.data[1:12]
      | selectattr("precipProbability", "gt", 0.2) | list | selectattr("precipIntensity",
      "gt", 0.0) | list | length > 0 }}'
  action:
  - data:
      message: Stäng fönster och ta in dynor.
      title: Rain during night
    service: notify.pushbullet_notifier
- id: '1531143646436'
  alias: Upcoming rain alert
  trigger:
  - platform: template
    value_template: '{{ states.sensor.rain_probability.attributes.hourly.data[1:3]
      | selectattr("precipProbability", "gt", 0.2) | list | selectattr("precipIntensity",
      "gt", 0.0) | list | length > 0 }}'
  condition: []
  action:
  - data:
      message: It will probably rain soon
      title: Rain alert
    service: notify.pushbullet_notifier
- id: '1531325215883'
  alias: Welcome home
  trigger:
  - entity_id: device_tracker.huawei_mate_9_pro9daa4a7
    from: not_home
    platform: state
    to: home
  condition: []
  action:
  - data:
      message: Du är kung :)
      title: Välkommen hem
    service: notify.pushbullet_notifier
- id: '1532183349901'
  alias: Sunset
  trigger:
  - event: sunset
    offset: -00:30
    platform: sun
  condition: []
  action:
  - data:
      brightness_pct: 30
      entity_id: light.gateway_light_7811dcdf0cfa
      kelvin: 2000
    service: light.turn_on
- id: '1532183940727'
  alias: Sunrise
  trigger:
  - event: sunrise
    offset: 00:15
    platform: sun
  condition: []
  action:
  - data:
      entity_id: light.gateway_light_7811dcdf0cfa
    service: light.turn_off
- id: '1533203159068'
  alias: Front door opens
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d0002049a62
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      gw_mac: 78:11:DC:DF:0C:FA
      ringtone_id: 29
      ringtone_vol: 8
    service: xiaomi_aqara.play_ringtone
  - delay: 00:00:01
  - data:
      gw_mac: 78:11:DC:DF:0C:FA
    service: xiaomi_aqara.stop_ringtone
- id: '1533203776840'
  alias: Light test
  trigger:
  - entity_id: light.tradfri_bulb_e14_ws_opal_400lm
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      brightness_pct: 30
      entity_id: light.gateway_light_7811dcdf0cfa
      rgb_color:
      - 255
      - 161
      - 75
    service: light.turn_on
- id: '1533223349979'
  alias: Terrass doors opens
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d000204bac9
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: binary_sensor.door_window_sensor_158d0002048620
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      gw_mac: 78:11:DC:DF:0C:FA
      ringtone_id: 20
      ringtone_vol: 8
    service: xiaomi_aqara.play_ringtone
  - delay:
      milliseconds: 850
  - data:
      gw_mac: 78:11:DC:DF:0C:FA
    service: xiaomi_aqara.stop_ringtone
