- id: '1531068777832'
  alias: Nightly rain
  initial_state: 'off'
  trigger:
  - at: '21:00'
    platform: time
  condition:
  - condition: template
    value_template: '{% set p = states.sensor.rain_probability.attributes.hourly.data[1:12]
      | map(attribute="precipProbability") | list %}


      {% set pNoRain = (1 - p[0]) * (1 - p[1]) * (1 - p[2]) * (1 - p[3]) * (1 - p[4])
      * (1 - p[5]) * (1 - p[6]) * (1 - p[7]) * (1 - p[8]) * (1 - p[9]) * (1 - p[10])
      %}


      {{ (1 - pNoRain) >= 0.2 }}'
  action:
  - data:
      message: Stäng fönster och ta in dynor.
      title: Rain during night
    service: notify.pushbullet_notifier
- id: '1531143646436'
  alias: Upcoming rain alert
  initial_state: 'off'
  trigger:
  - platform: template
    value_template: '{% set p = states.sensor.rain_probability.attributes.hourly.data[1:4]
      | map(attribute="precipProbability") | list %}


      {% set pNoRain = (1 - p[0]) * (1 - p[1]) * (1 - p[2]) %}


      {{ (1 - pNoRain) >= 0.15 }}'
  condition:
  - condition: template
    value_template: "{{ \n(states.automation.upcoming_rain_alert.attributes.last_triggered\
      \ == None) or\n\n(as_timestamp(now()) - as_timestamp(states.automation.upcoming_rain_alert.attributes.last_triggered))\
      \ / 60  > 180 }}"
  action:
  - data:
      message: It will probably rain soon
      title: Rain alert
    service: notify.pushbullet_notifier
- id: '1532183349901'
  alias: Sunset
  initial_state: 'on'
  trigger:
  - event: sunset
    offset: -00:30
    platform: sun
  condition: []
  action:
  - data:
      brightness_pct: 10
      entity_id: light.gateway_light_7811dcdf0cfa
      rgb_color:
      - 255
      - 255
      - 35
    service: light.turn_on
  - data:
      brightness_pct: '100'
      entity_id: light.yeelight_color2_7c49ebb91e8a
      kelvin: 2700
    service: light.turn_on
  - data:
      brightness_pct: '100'
      entity_id: light.yeelight_color2_7c49ebb9114a
    service: light.turn_on
  - data:
      entity_id: switch.light_livingroom_1
    service: switch.turn_on
  - data:
      entity_id: switch.light_livingroom_2
    service: switch.turn_on
- id: '1532183940727'
  alias: Sunrise
  initial_state: 'on'
  trigger:
  - event: sunrise
    offset: 00:15
    platform: sun
  condition: []
  action:
  - data:
      entity_id: light.gateway_light_7811dcdf0cfa
    service: light.turn_off
  - data:
      entity_id: light.yeelight_color2_7c49ebb91e8a
    service: light.turn_off
  - data:
      entity_id: light.yeelight_color2_7c49ebb9114a
    service: light.turn_off
  - data:
      entity_id: switch.light_livingroom_1
    service: switch.turn_off
  - data:
      entity_id: switch.light_livingroom_2
    service: switch.turn_off
- id: '1533203159068'
  alias: Front door opens
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d0002049a62
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.silent_mode
    state: 'off'
  action:
  - data:
      gw_mac: 04:CF:8C:91:62:CB
      ringtone_id: 29
      ringtone_vol: 8
    service: xiaomi_aqara.play_ringtone
  - delay: 00:00:01
  - data:
      gw_mac: 04:CF:8C:91:62:CB
    service: xiaomi_aqara.stop_ringtone
  initial_state: 'on'
- id: '1533223349979'
  alias: Terrass doors opens
  initial_state: 'on'
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d000204bac9
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: binary_sensor.door_window_sensor_158d0002048620
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: binary_sensor.door_window_sensor_158d00022eff91
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.silent_mode
    state: 'off'
  action:
  - data:
      gw_mac: 78:11:DC:DF:0C:FA
      ringtone_id: 20
      ringtone_vol: 8
    service: xiaomi_aqara.play_ringtone
  - delay:
      milliseconds: 850
  - data:
      gw_mac: 78:11:DC:DF:0C:FA
    service: xiaomi_aqara.stop_ringtone
- id: '1535117514847'
  alias: Play media
  initial_state: 'on'
  trigger:
  - entity_id: media_player.vardagsrum
    platform: state
    to: playing
  condition:
  - condition: state
    entity_id: group.tv_room_rgb_lights
    state: 'on'
  - after: '18:00'
    before: 06:00
    condition: time
  action:
  - data:
      brightness_pct: 10
      entity_id: group.tv_room_rgb_lights
      kelvin: 3000
    service: light.turn_on
- id: '1535128483194'
  alias: Stop media
  initial_state: 'on'
  trigger:
  - entity_id: media_player.vardagsrum
    for:
      hours: 0
      minutes: 0
      seconds: 10
    from: playing
    platform: state
    to: idle
  - entity_id: media_player.vardagsrum
    for:
      hours: 0
      minutes: 0
      seconds: 10
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: group.tv_room_rgb_lights
    state: 'on'
  - after: '18:00'
    before: 06:00
    condition: time
  action:
  - data:
      entity_id: script.1536574687151
    service: script.turn_on
- id: '1536864983273'
  alias: Fire alarm
  initial_state: 'on'
  trigger:
  - entity_id: binary_sensor.smoke_sensor_158d00023117bb
    platform: state
    to: 'on'
  - entity_id: binary_sensor.smoke_sensor_158d000215ab06
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: Possible fire in kitchen/tvroom
      title: Possible fire
    service: notify.pushbullet_notifier
- id: '1536961274860'
  alias: Coming home
  trigger:
  - entity_id: device_tracker.johannas_mobil
    platform: state
    to: home
  - entity_id: device_tracker.huawei_mate_9_pro9daa4a7
    platform: state
    to: home
  - entity_id: group.trusted_people
    platform: state
    to: home
  condition: []
  action:
  - data:
      entity_id: group.hallway_lights
    service: light.turn_on
  - data:
      entity_id: input_boolean.alarm_state
    service: input_boolean.turn_off
  - data:
      entity_id: input_boolean.identification_pending
    service: input_boolean.turn_off
  initial_state: 'on'
- id: '1538080363136'
  alias: Leaving home
  trigger:
  - entity_id: group.trusted_people
    from: home
    platform: state
    to: not_home
  condition:
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
  action:
  - data:
      entity_id: group.tv_room_rgb_lights
    service: light.turn_off
  - data:
      entity_id: group.hallway_lights
    service: light.turn_off
  - data:
      entity_id: switch.kaffebryggaren
    service: switch.turn_off
  - data:
      entity_id: input_boolean.alarm_state
    service: input_boolean.turn_on
  - data:
      entity_id: light.tv_room_cieling_lights
    service: light.turn_off
  initial_state: 'on'
- id: '1540397582929'
  alias: Sleeping
  trigger:
  - entity_id: input_boolean.sleeping
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: light.yeelight_color2_7c49ebb91e8a
    service: light.turn_off
  - data:
      entity_id: group.tv_room_rgb_lights
    service: light.turn_off
  - data:
      entity_id: light.yeelight_color2_7c49ebb9114a
    service: light.turn_off
  - data:
      entity_id: switch.light_livingroom_1
    service: switch.turn_off
  - data:
      entity_id: switch.light_livingroom_2
    service: switch.turn_off
  - data:
      entity_id: input_boolean.silent_mode
    service: input_boolean.turn_off
  - data:
      entity_id: input_boolean.tv_room_light_switched_recently_pressed
    service: input_boolean.turn_off
  initial_state: 'on'
- id: '1540397737368'
  alias: Waking up
  initial_state: 'on'
  trigger:
  - entity_id: input_boolean.sleeping
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - condition: or
    conditions:
    - before: sunrise
      condition: sun
    - after: sunset
      condition: sun
  action:
  - data:
      brightness_pct: '100'
      entity_id: light.yeelight_color2_7c49ebb91e8a
      kelvin: 2700
    service: light.turn_on
  - data:
      brightness_pct: '100'
      entity_id: light.yeelight_color2_7c49ebb9114a
    service: light.turn_on
  - data:
      entity_id: switch.light_livingroom_1
    service: switch.turn_on
  - data:
      entity_id: switch.light_livingroom_2
    service: switch.turn_on
  - data:
      entity_id: input_boolean.alarm_state
    service: input_boolean.turn_off
- id: '1541183654317'
  alias: Coffee maker
  initial_state: 'on'
  trigger:
  - entity_id: switch.kaffebryggaren
    for: '1800'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: switch.kaffebryggaren
    service: switch.turn_off
- id: '1547903815352'
  alias: On reboot
  initial_state: 'on'
  trigger:
  - event: start
    platform: homeassistant
  condition:
  - condition: state
    entity_id: group.trusted_people
    state: not_home
  action:
  - data:
      entity_id: input_boolean.alarm_state
    service: input_boolean.turn_on
- id: '1550599967723'
  alias: Turn on stereo
  trigger:
  - entity_id: media_player.overvaning
    platform: state
    to: 'on'
  - entity_id: media_player.overvaning
    platform: state
    to: playing
  - entity_id: media_player.overvaning
    from: 'off'
    platform: state
    to: idle
  condition: []
  action:
  - data:
      entity_id: switch.stereo
    service: switch.turn_on
- id: '1550600530907'
  alias: Turn off stereo
  trigger:
  - entity_id: media_player.overvaning
    platform: state
    to: 'off'
  - entity_id: media_player.overvaning
    for: 00:15:00
    platform: state
    to: idle
  - entity_id: media_player.overvaning
    for: 00:15:00
    platform: state
    to: paused
  condition: []
  action:
  - data:
      entity_id: switch.stereo
    service: switch.turn_off
- id: '1555055523241'
  alias: Alarm off
  trigger:
  - entity_id: input_boolean.sleeping
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: input_boolean.alarm_state
    service: input_boolean.turn_off
- id: '1557508975938'
  alias: Basement door opens
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d000313441b
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: light.gateway_light_04cf8c9162cb
    service: light.turn_on
- id: '1557509032847'
  alias: Basement door closes
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d000313441b
    for: 00:01:00
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: light.gateway_light_04cf8c9162cb
    service: light.turn_off
- id: '1558249105875'
  alias: Sitting at the desk
  trigger:
  - event_data:
      entity_id: binary_sensor.vibration_158d0002afd810
      movement_type: tilt
    event_type: xiaomi_aqara.movement
    platform: event
  condition: []
  action:
  - data:
      brightness_pct: 100
      entity_id: light.yeelight_color2_7c49ebb91e8a
    service: light.turn_on
- id: '1558408108538'
  alias: Awaiting identification
  trigger:
  - entity_id: group.house_shell
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: group.trusted_people
    state: not_home
  action:
  - data:
      entity_id: input_boolean.identification_pending
    service: input_boolean.turn_on
- id: '1558638170121'
  alias: Doorbell ringing
  trigger:
  - event_data:
      click_type: single
      entity_id: binary_sensor.switch_doorbell
    event_type: xiaomi_aqara.click
    platform: event
  condition: []
  action:
  - data:
      entity_id: input_boolean.doorbell_ringing
    service: input_boolean.turn_on
  - delay: 00:00:15
  - data:
      entity_id: input_boolean.doorbell_ringing
    service: input_boolean.turn_off
- id: '1561036012875'
  alias: Turn on alarm when sleeping
  trigger:
  - entity_id: input_boolean.sleeping
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
  action:
  - data:
      entity_id: input_boolean.alarm_state
    service: input_boolean.turn_on
- id: '1561103142057'
  alias: Water leak
  trigger:
  - entity_id: binary_sensor.water_leak_sensor_158d0002334525
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: binary_sensor.water_leak_sensor_158d00027955e3
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: Bathroom or basement
      title: Water Leak alert
    service: notify.pushbullet_notifier
- id: '1561320522889'
  alias: Play media - cieling
  trigger:
  - entity_id: media_player.vardagsrum
    platform: state
    to: playing
  condition:
  - after: '18:00'
    before: 06:00
    condition: time
  - condition: state
    entity_id: light.tv_room_cieling_lights
    state: 'on'
  action:
  - data:
      entity_id: light.yeelight_ceiling3_04cf8c9adab1
      mode: moonlight
    service: yeelight.set_mode
  - data:
      entity_id: light.yeelight_ceiling3_04cf8c9b01f8
      mode: moonlight
    service: yeelight.set_mode
  - data:
      brightness_pct: 5
      entity_id: light.tv_room_cieling_lights
    service: light.turn_on
- id: '1561567490842'
  alias: Stop media - cieling
  trigger:
  - entity_id: media_player.vardagsrum
    for: 0:00:10
    from: playing
    platform: state
    to: idle
  - entity_id: media_player.vardagsrum
    for: 0:00:10
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: light.tv_room_cieling_lights
    state: 'on'
  - after: '18:00'
    before: 06:00
    condition: time
  action:
  - data:
      entity_id: light.yeelight_ceiling3_04cf8c9adab1
      mode: moonlight
    service: yeelight.set_mode
  - data:
      entity_id: light.yeelight_ceiling3_04cf8c9b01f8
      mode: moonlight
    service: yeelight.set_mode
  - data:
      brightness_pct: '100'
      entity_id: light.tv_room_cieling_lights
    service: light.turn_on
  - delay: 00:01:00
  - data:
      entity_id: light.yeelight_ceiling3_04cf8c9b01f8
      mode: normal
    service: yeelight.set_mode
  - data:
      entity_id: light.yeelight_ceiling3_04cf8c9adab1
      mode: normal
    service: yeelight.set_mode
  - data:
      brightness_pct: '10'
      entity_id: light.tv_room_cieling_lights
      kelvin: 2000
    service: light.turn_on
- id: '1561735682681'
  alias: Guest arrived
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d0002049a62
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: group.trusted_people
    state: not_home
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'on'
  action:
  - delay: 00:05:00
  - condition: state
    entity_id: group.trusted_people
    state: not_home
  - data:
      message: A guest arrived while noone was home
      title: Guest arrived
    service: notify.pushbullet_notifier
- id: '1562184118629'
  alias: Mark Tv-room lights as manually set
  trigger:
  - event_data:
      click_type: single
      entity_id: binary_sensor.switch_158d000215c957
    event_type: xiaomi_aqara.click
    platform: event
  - event_data:
      click_type: single
      entity_id: binary_sensor.switch_158d000215c8ca
    event_type: xiaomi_aqara.click
    platform: event
  condition: []
  action:
  - data:
      entity_id: input_boolean.tv_room_light_switched_recently_pressed
    service: input_boolean.turn_on
- id: '1562185409909'
  alias: 'Reset tv-room light manual mark '
  trigger:
  - entity_id: input_boolean.tv_room_light_switched_recently_pressed
    for: 02:00:00
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: input_boolean.tv_room_light_switched_recently_pressed
    service: input_boolean.turn_off
- id: '1562186516375'
  alias: Manual alarm arming
  trigger:
  - entity_id: input_boolean.alarm_arming_pending
    for: 00:02:00
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: input_boolean.alarm_arming_pending
    service: input_boolean.turn_off
  - data:
      entity_id: input_boolean.alarm_state
    service: input_boolean.turn_on
- id: '1562190311457'
  alias: Good morning notification
  trigger:
  - entity_id: input_boolean.sleeping
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - after: 06:00
    before: 08:00
    condition: time
  action:
  - data:
      entity_id: input_boolean.notification_goodmorning
    service: input_boolean.turn_on
- id: '1562220236800'
  alias: Clear good morning notification
  trigger:
  - entity_id: binary_sensor.motion_sensor_kitchen
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - delay: 00:00:05
  - data:
      entity_id: input_boolean.notification_goodmorning
    service: input_boolean.turn_off
- id: '1562224730116'
  alias: Trigger alarm
  trigger:
  - entity_id: group.motion_sensors
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: group.house_shell
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.alarm_state
    state: 'on'
  action:
  - data:
      entity_id: input_boolean.alarm_triggered
    service: input_boolean.turn_on
