- id: '1531068777832'
  alias: Nightly rain
  trigger:
  - at: '21:00'
    platform: time
  condition:
  - condition: template
    value_template: '{% set p = states.sensor.rain_probability.attributes.hourly.data[1:12]
      | map(attribute="precipProbability") | list %}


      {% set pNoRain = (1 - p[0]) * (1 - p[1]) * (1 - p[2]) * (1 - p[3]) * (1 - p[4])
      * (1 - p[5]) * (1 - p[6]) * (1 - p[7]) * (1 - p[8]) * (1 - p[9]) * (1 - p[10])
      %}


      {{ (1 - pNoRain) >= 0.2 }}'
  action:
  - data:
      message: Stäng fönster och ta in dynor.
      title: Rain during night
    service: notify.pushbullet_notifier
- id: '1531143646436'
  alias: Upcoming rain alert
  trigger:
  - platform: template
    value_template: '{% set p = states.sensor.rain_probability.attributes.hourly.data[1:4]
      | map(attribute="precipProbability") | list %}


      {% set pNoRain = (1 - p[0]) * (1 - p[1]) * (1 - p[2]) %}


      {{ (1 - pNoRain) >= 0.15 }}'
  condition:
  - condition: template
    value_template: "{{ \n(states.automation.upcoming_rain_alert.attributes.last_triggered\
      \ == None) or\n\n(as_timestamp(now()) - as_timestamp(states.automation.upcoming_rain_alert.attributes.last_triggered))\
      \ / 60  > 180 }}"
  action:
  - data:
      message: It will probably rain soon
      title: Rain alert
    service: notify.pushbullet_notifier
- id: '1532183349901'
  alias: Sunset
  trigger:
  - event: sunset
    offset: -00:30
    platform: sun
  condition: []
  action:
  - data:
      brightness_pct: 10
      entity_id: light.gateway_light_7811dcdf0cfa
      rgb_color:
      - 255
      - 255
      - 35
    service: light.turn_on
- id: '1532183940727'
  alias: Sunrise
  trigger:
  - event: sunrise
    offset: 00:15
    platform: sun
  condition: []
  action:
  - data:
      entity_id: light.gateway_light_7811dcdf0cfa
    service: light.turn_off
- id: '1533203159068'
  alias: Front door opens
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d0002049a62
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      gw_mac: 78:11:DC:DF:0C:FA
      ringtone_id: 29
      ringtone_vol: 8
    service: xiaomi_aqara.play_ringtone
  - delay: 00:00:01
  - data:
      gw_mac: 78:11:DC:DF:0C:FA
    service: xiaomi_aqara.stop_ringtone
- id: '1533203776840'
  alias: Labb
  trigger:
  - event_data:
      click_Type: single
      entity_id: binary_sensor.switch_doorbell
    event_type: click
    platform: event
  condition: []
  action:
  - data_template:
      ringtone: 10
      volume: 50
    service: script.1537340978223
- id: '1533223349979'
  alias: Terrass doors opens
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d000204bac9
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: binary_sensor.door_window_sensor_158d0002048620
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: binary_sensor.door_window_sensor_158d00022eff91
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      gw_mac: 78:11:DC:DF:0C:FA
      ringtone_id: 20
      ringtone_vol: 8
    service: xiaomi_aqara.play_ringtone
  - delay:
      milliseconds: 850
  - data:
      gw_mac: 78:11:DC:DF:0C:FA
    service: xiaomi_aqara.stop_ringtone
- id: '1533571966905'
  alias: Alarm
  trigger:
  - entity_id: group.doors
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: light.tradfri_bulb_e14_ws_opal_400lm
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: group.motion_sensors
    platform: state
    to: 'on'
  - entity_id: group.closed_windows
    platform: state
    to: 'on'
  - entity_id: binary_sensor.door_window_sensor_158d00022f151e
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: template
    value_template: "{{ \n(states.automation.alarm.attributes.last_triggered == None)\
      \ or\n\n(as_timestamp(now()) - as_timestamp(states.automation.alarm.attributes.last_triggered))\
      \ / 60  > 15 }}"
  action:
  - delay: 00:01:00
  - condition: or
    conditions:
    - condition: and
      conditions:
      - condition: state
        entity_id: group.trusted_people
        state: not_home
    - after: '23:00'
      before: 06:00
      condition: time
  - data:
      message: Larm triggat
      title: Larm triggat
    service: notify.pushbullet_notifier
- id: '1535117514847'
  alias: 'Play media '
  trigger:
  - entity_id: media_player.vardagsrum
    platform: state
    to: playing
  condition:
  - condition: state
    entity_id: group.tv_room_rgb_lights
    state: 'on'
  - after: '18:00'
    before: 06:00
    condition: time
  action:
  - data:
      brightness_pct: 10
      entity_id: group.tv_room_rgb_lights
      kelvin: 3000
    service: light.turn_on
- id: '1535128483194'
  alias: 'Stop media '
  trigger:
  - entity_id: media_player.vardagsrum
    for:
      hours: 0
      minutes: 0
      seconds: 10
    from: playing
    platform: state
    to: idle
  - entity_id: media_player.vardagsrum
    for:
      hours: 0
      minutes: 0
      seconds: 10
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: group.tv_room_rgb_lights
    state: 'on'
  - after: '18:00'
    before: 06:00
    condition: time
  action:
  - data:
      entity_id: script.1536574687151
    service: script.turn_on
- id: '1535392175542'
  alias: 'No motion '
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d00023db75a
    for:
      hours: 1
      minutes: 0
      seconds: 0
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: media_player.vardagsrum
    state: 'off'
  action:
  - data:
      entity_id: group.tv_room_rgb_lights
    service: light.turn_off
- id: '1536864983273'
  alias: 'Fire alarm '
  trigger:
  - entity_id: binary_sensor.smoke_sensor_158d00023117bb
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: Possible fire in kitchen
      title: Possible fire
    service: notify.pushbullet_notifier
- id: '1536961274860'
  alias: Coming home
  trigger:
  - entity_id: group.trusted_people
    platform: state
    to: home
  condition:
  - after: sunset
    condition: sun
  action:
  - data:
      entity_id: group.hallway_lights
    service: light.turn_on
