
homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 59.2672456
  longitude: 15.374619
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 29
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  # Customization file
  customize: !include customize.yaml
  auth_providers:
   - type: legacy_api_password

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123
  #ssl_certificate: /home/homeassistant/dehydrated/certs/villasundbyvik.duckdns.org/fullchain.pem
  #ssl_key: /home/homeassistant/dehydrated/certs/villasundbyvik.duckdns.org/privkey.pem
  #base_url: villasundbyvik.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

device_tracker:
  - platform: unifi_direct
    host: 192.168.10.179
    consider_home: 120
    username: !secret unifi_ap_username
    password: !secret unifi_ap_password
    new_device_defaults:
      hide_if_away: true
  - platform: unifi_direct
    host: 192.168.10.238
    consider_home: 120
    username: !secret unifi_ap_username
    password: !secret unifi_ap_password

notify:
  - name: Pushbullet_notifier
    platform: pushbullet
    api_key: !secret pushbullet_secret

sensor:
  - platform: yr
  - platform: rest
    name: rain probability
    scan_interval: 600
    resource: !secret darksky_forecast_url
    unit_of_measurement: "%"
    value_template: '{{ value_json.hourly.data[1].precipProbability }}'
    json_attributes:
      - hourly
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /home
      - type: memory_free
      - type: processor_use  
  - platform: tibber
    access_token: !secret tibber_token
  - platform: darksky
    forecast:
      - 1
    api_key: !secret dark_sky_key
    monitored_conditions:
      - summary
      - precip_type
      - precip_probability
      - precip_intensity
      - precip_accumulation 
      - temperature
      - wind_speed
      - wind_bearing
      - cloud_cover
      - humidity
      - temperature_max
      - temperature_min
      - icon
      - apparent_temperature
    update_interval: '00:15'

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomi_gateway_key

ifttt:
  key: 9Rfbtkpj63qmsIkv2itVz2tEpnr2Unj0tSgNclbkNx

media_player: 
  - platform: lg_soundbar
    name: Soundbar

input_boolean:
  alarm_state:
    name: Larm
    initial: off
    icon: mdi:bell
  alarm_triggered:
    name: Larm utlöst
    initial: off
  sleeping:
    name: Sover
    initial: off
  silent_mode:
    name: "Tyst läge"
    initial: off
    icon: mdi:bell-off
  guest_mode:
    name: Gästläge
    initial: off
    icon: mdi:account-multiple
  testing:
    name: testing
    initial: off

input_select:
  light_presets:
    name: Ljusmiljö
    options:
     - Normal
     - Halloween
     - Rotate
    initial: Rotate
    icon: mdi:panda

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

