
homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 59.2672456
  longitude: 15.374619
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 29
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  # Customization file
  customize: !include customize.yaml
  auth_providers:
   - type: homeassistant
   - type: legacy_api_password
     api_password: !secret http_password

system_health:

# Enables the frontend
frontend:
  themes: !include themes.yaml

# Enables configuration UI
config:
  themes: !include themes.yaml

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123
  #ssl_certificate: /home/homeassistant/dehydrated/certs/villasundbyvik.duckdns.org/fullchain.pem
  #ssl_key: /home/homeassistant/dehydrated/certs/villasundbyvik.duckdns.org/privkey.pem
  #base_url: villasundbyvik.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# Cloud
cloud:

device_tracker:
  - platform: unifi_direct
    host: 192.168.10.179
    consider_home: 120
    username: !secret unifi_ap_username
    password: !secret unifi_ap_password
    new_device_defaults:
      hide_if_away: true
  - platform: unifi_direct
    host: 192.168.10.239
    consider_home: 120
    username: !secret unifi_ap_username
    password: !secret unifi_ap_password

notify:
  - name: Pushbullet_notifier
    platform: pushbullet
    api_key: !secret pushbullet_secret

weather:
  - platform: darksky
    api_key: !secret dark_sky_key

sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'time_date'
  - platform: rest
    name: rain probability
    scan_interval: 600
    resource: !secret darksky_forecast_url
    unit_of_measurement: "%"
    value_template: '{{ value_json.hourly.data[1].precipProbability }}'
    json_attributes:
      - hourly
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /home
      - type: memory_free
      - type: processor_use  
  - platform: tibber
    access_token: !secret tibber_token
  - platform: darksky
    forecast:
      - 1
    api_key: !secret dark_sky_key
    scan_interval:
      minutes: 15
    monitored_conditions:
      - summary
      - precip_type
      - precip_probability
      - precip_intensity
      - precip_accumulation 
      - temperature
      - wind_speed
      - wind_bearing
      - cloud_cover
      - humidity
      - temperature_max
      - temperature_min
      - icon
      - apparent_temperature
  

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - mac: 78:11:DC:DF:0C:FA
      key: !secret xiaomi_gateway_key
    - mac: 04:CF:8C:91:62:CB
      key: !secret xiaomi_gateway_downstairs_key
ifttt:
  key: 9Rfbtkpj63qmsIkv2itVz2tEpnr2Unj0tSgNclbkNx

media_player: 
  - platform: lg_soundbar
    name: Soundbar

input_boolean:
  alarm_state:
    name: Larm
    icon: mdi:bell
  alarm_triggered:
    name: Larm utlöst
  sleeping:
    name: Sover
  silent_mode:
    name: "Tyst läge"
    icon: mdi:bell-off
  guest_mode:
    name: Gästläge
    icon: mdi:account-multiple
  testing:
    name: testing
  identification_pending:
    name: Waiting for identification
  doorbell_ringing:
    name: Doorbell is ringing  

input_select:
  light_presets:
    name: Ljusmiljö
    options:
     - Normal
     - Halloween
     - Rotate
    initial: Rotate
    icon: mdi:panda


light:
  - platform: group
    name: Tvroom_lights
    entities:
      - light.yeelight_color2_7c49ebb319e7
      - light.yeelight_color2_7c49ebb31c16
  - platform: group
    name: Hallway_lights
    entities:
      - light.tradfri_bulb_e14_ws_opal_400lm
      - light.tradfri_bulb_e14_ws_opal_400lm_2


camera:
  - platform: generic
    still_image_url: http://194.218.96.92/jpg/image.jpg

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

